"""empty message

Revision ID: 04daf1db6c43
Revises: 
Create Date: 2020-05-26 06:10:56.810045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04daf1db6c43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
